"""empty message

Revision ID: 58ccb31a84cd
Revises: 932a1b3ae7ea
Create Date: 2021-02-11 01:08:43.804392

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '58ccb31a84cd'
down_revision = '932a1b3ae7ea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('image', sa.String(length=128), nullable=True))
    op.create_unique_constraint(None, 'user', ['image'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_column('user', 'image')
    # ### end Alembic commands ###
