"""empty message

Revision ID: 6327c01a21bb
Revises: a1a123c09c09
Create Date: 2021-01-23 00:50:36.434009

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6327c01a21bb'
down_revision = 'a1a123c09c09'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_movie_timestamp'), 'movie', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_movie_timestamp'), table_name='movie')
    # ### end Alembic commands ###
