"""empty message

Revision ID: 641ee857a580
Revises: 4796c559c621
Create Date: 2021-01-21 16:13:14.807577

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '641ee857a580'
down_revision = '4796c559c621'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('movie',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=256), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_movie_title'), 'movie', ['title'], unique=False)
    op.create_index(op.f('ix_movie_year'), 'movie', ['year'], unique=False)
    op.create_table('review',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('grade', sa.Integer(), nullable=True),
    sa.Column('thoughts', sa.Text(), nullable=True),
    sa.Column('feelings', sa.Text(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('movie_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['movie_id'], ['movie.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_review_grade'), 'review', ['grade'], unique=False)
    op.add_column('user', sa.Column('joined', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'joined')
    op.drop_index(op.f('ix_review_grade'), table_name='review')
    op.drop_table('review')
    op.drop_index(op.f('ix_movie_year'), table_name='movie')
    op.drop_index(op.f('ix_movie_title'), table_name='movie')
    op.drop_table('movie')
    # ### end Alembic commands ###
