"""empty message

Revision ID: 78aece093c53
Revises: a8b560d08c5e
Create Date: 2021-02-18 05:56:43.584846

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '78aece093c53'
down_revision = 'a8b560d08c5e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('movie_request',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('other_info', sa.Text(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_movie_request_timestamp'), 'movie_request', ['timestamp'], unique=False)
    op.create_index(op.f('ix_movie_request_user_id'), 'movie_request', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_movie_request_user_id'), table_name='movie_request')
    op.drop_index(op.f('ix_movie_request_timestamp'), table_name='movie_request')
    op.drop_table('movie_request')
    # ### end Alembic commands ###
